use_frameworks!

platform :ios, '14.0'

target 'IOSIAPHandler_Example' do
  pod 'IOSIAPHandler', :path => '../'

  target 'IOSIAPHandler_Tests' do
    inherit! :search_paths

    pod 'Alamofire'
    pod 'FirebaseAnalytics'
    pod 'Adjust'
    pod 'SVProgressHUD'
    
  end
end
